"""
Numerical verification of the *rate-thinning* description of beam
declustering, for Sec. 3.2a of GPD_beam_and_declustering_v4.md.

Background
----------
A first attempt modelled declustering as competition against n_eff
independent draws, giving F_pk = F_pix^{n_eff}.  That caricature matches
the peak median by construction (it is how q_* is defined in Sec. 3.7) but
misses the rest of the peak CDF by up to 0.08, and it badly under-predicts
the pixel-vs-peak difference in the conditional survival ratio.  The
present script tests the correct tail description.

Theory under test
-----------------
Far above the core the tail is generated by isolated bright objects.  An
object whose *peak* value is D0 deposits pixel values D0 * rho(theta_j)
over its footprint, where rho is the beam profile b (for a source-dominated
tail) or the field autocorrelation (for a Gaussian random field).  If the
peak tail is regularly varying, Fbar_pk(D) = c D^{-1/xi}, then

    N_pix(>D) / N_pk(>D)  ->  C  =  (1/A_pix) * Integral rho(theta)^{1/xi} d2theta

which for a Gaussian rho of width sigma_rho evaluates to

    C  =  xi * Omega_rho / A_pix,      Omega_rho = 2 pi sigma_rho^2.

Two claims follow:

T1.  C is *independent of D*.  Hence declustering multiplies the tail
     exceedance rate by a constant and leaves the conditional excess
     distribution -- the only thing the POT likelihood sees -- unchanged.
     So xi(pixels) = xi(peaks) and sigma(pixels) = sigma(peaks).

T2.  The closed form for C is right:
       - confusion field (source-dominated tail):  sigma_rho = sigma_b
       - Gaussian random field:  sigma_rho = sqrt(2) sigma_b, because the
         mean profile around a high peak of a GRF is its autocorrelation
         function, which for beam-smoothed white noise is a Gaussian of
         width sqrt(2) sigma_b (so Omega_rho = 2 Omega_beam).

     Where xi is not constant with threshold (a Gaussian tail, where the
     local index steepens as xi_eff = 1/D^2 in sigma units), C must *drift*
     with u -- and that drift is exactly the residual pixel-vs-peak
     disagreement seen in Table 4.4.

Run:  python3 verify_rate_thinning.py
"""

# %% imports and configuration
import numpy as np
from scipy.ndimage import gaussian_filter, maximum_filter
from scipy.optimize import minimize

RNG = np.random.default_rng(20260813)

BEAM_FWHM_PIX = 5.0                                  # 20" beam, 4" pixels
SIGMA_B = BEAM_FWHM_PIX / np.sqrt(8.0 * np.log(2.0))  # 2.1233 px
OMEGA_BEAM = 2.0 * np.pi * SIGMA_B**2                 # 28.33 px^2
FILTER_SIZE = 5
NSIDE = 2048
NMAPS = 12                       # more maps than v1: the far tail was noisy


# %% helpers
def declustered_peaks(map2d, size=FILTER_SIZE):
    m = np.where(np.isfinite(map2d), map2d, -np.inf)
    return map2d[(m == maximum_filter(m, size=size)) & np.isfinite(map2d)]


def gpd_nll(theta, y):
    xi, log_sigma = theta
    sigma = np.exp(log_sigma)
    z = 1.0 + xi * y / sigma
    if np.any(z <= 0):
        return np.inf
    if abs(xi) < 1e-8:
        return y.size * log_sigma + y.sum() / sigma
    return y.size * log_sigma + (1.0 + 1.0 / xi) * np.log(z).sum()


def fit_gpd(y):
    """MLE for GPD exceedances; returns (xi, sigma, n, se_xi)."""
    y = np.asarray(y, float)
    y = y[y > 0]
    if y.size < 30:
        return np.nan, np.nan, y.size, np.nan
    res = minimize(gpd_nll, x0=[0.1, np.log(y.std() + 1e-12)], args=(y,),
                   method="Nelder-Mead",
                   options={"xatol": 1e-6, "fatol": 1e-9, "maxiter": 5000})
    xi = res.x[0]
    return xi, np.exp(res.x[1]), y.size, (1.0 + xi) / np.sqrt(y.size)


# %% field generators
def gaussian_field(nside, rng):
    """Beam-smoothed white noise, normalised to unit variance."""
    f = gaussian_filter(rng.normal(size=(nside, nside)), sigma=SIGMA_B,
                        mode="wrap")
    return f / f.std()


def confusion_field(nside, rng, n_beam=12.6, alpha=1.6, beta=3.8,
                    s_break=4.0, s_min=1e-3, s_cut=100.0):
    """Poisson DPL source population, beam smoothed, in mJy/beam."""
    nsrc = int(round(n_beam * nside**2 / OMEGA_BEAM))
    grid = np.geomspace(s_min, s_cut, 4000)
    dnds = np.where(grid < s_break, grid**(-alpha),
                    s_break**(beta - alpha) * grid**(-beta))
    cdf = np.concatenate([[0.0], np.cumsum(0.5 * (dnds[1:] + dnds[:-1])
                                           * np.diff(grid))])
    cdf /= cdf[-1]
    fluxes = np.interp(rng.random(nsrc), cdf, grid)
    raw = np.zeros((nside, nside))
    np.add.at(raw, (rng.integers(0, nside, nsrc),
                    rng.integers(0, nside, nsrc)), fluxes)
    return gaussian_filter(raw, sigma=SIGMA_B, mode="wrap") * OMEGA_BEAM


# %% main test
def run_case(name, generator, omega_rho, xi_is_local):
    print("\n" + "=" * 78)
    print(f"  {name}")
    print(f"  Omega_rho / A_pix = {omega_rho:.2f}")
    print("=" * 78)

    pix, pks = [], []
    for _ in range(NMAPS):
        m = generator(NSIDE, RNG)
        pix.append(m.ravel())
        pks.append(declustered_peaks(m))
    pix = np.sort(np.concatenate(pix))
    pks = np.sort(np.concatenate(pks))
    print(f"pixels = {pix.size:,}   peaks = {pks.size:,}   "
          f"peaks/pixel = {pks.size / pix.size:.5f}")

    print("\nT1/T2: rate thinning ratio C = N_pix(>u)/N_pk(>u), "
          "and the GPD parameters on both sides")
    print(f"{'Fbar_pix':>10} {'u':>9} {'C(meas)':>9} {'C(pred)':>9}"
          f" {'xi_pix':>9} {'xi_pk':>9} {'d(xi)':>8} {'se':>6}"
          f" {'sig_pix':>8} {'sig_pk':>8} {'ratio':>6}")
    for fb in [1e-2, 1e-3, 1e-4, 1e-5]:
        u = np.quantile(pix, 1.0 - fb)
        npix = int((pix > u).sum())
        npk = int((pks > u).sum())
        if npk < 30:
            continue
        xi_p, sg_p, n_p, se_p = fit_gpd(pix[pix > u] - u)
        xi_k, sg_k, n_k, se_k = fit_gpd(pks[pks > u] - u)
        # predicted C: local index xi_eff = 1/u^2 for a Gaussian tail
        # (u in sigma units), otherwise the fitted xi itself
        xi_for_C = 1.0 / u**2 if xi_is_local else xi_p
        print(f"{fb:>10.0e} {u:>9.3f} {npix / npk:>9.2f}"
              f" {xi_for_C * omega_rho:>9.2f}"
              f" {xi_p:>9.4f} {xi_k:>9.4f} {xi_k - xi_p:>+8.4f} {se_k:>6.3f}"
              f" {sg_p:>8.4f} {sg_k:>8.4f} {sg_k / sg_p:>6.3f}")

    # Is C flat in u?  Print it on a fine ladder without fitting.
    print("\n   C(u) on a fine ladder (flatness is the whole claim):")
    row_u, row_c = [], []
    for fb in np.geomspace(3e-2, 1e-5, 9):
        u = np.quantile(pix, 1.0 - fb)
        npk = int((pks > u).sum())
        if npk < 30:
            continue
        row_u.append(u)
        row_c.append(int((pix > u).sum()) / npk)
    print("      u   " + " ".join(f"{v:>7.2f}" for v in row_u))
    print("      C   " + " ".join(f"{v:>7.2f}" for v in row_c))


if __name__ == "__main__":
    # GRF: mean profile around a high peak is the autocorrelation of the
    # beam, a Gaussian of width sqrt(2) sigma_b  ->  Omega_rho = 2 Omega_beam
    run_case("Gaussian beam-smoothed random field (units of sigma)",
             gaussian_field, 2.0 * OMEGA_BEAM, xi_is_local=True)
    # Confusion field: the tail is single-source dominated, so the profile
    # is the beam itself  ->  Omega_rho = Omega_beam
    run_case("Poisson confusion field, DPL, N_beam = 12.6 (mJy/beam)",
             confusion_field, OMEGA_BEAM, xi_is_local=False)
